In [1]:
# Aggregation on Ethnicity and Age Brackets

import pandas as pd

df_90 = pd.read_excel(r"C:\Users\ASYIKIN\OneDrive\Desktop\PYTHON FOR DATA ANALYSIS\PROJECTS\Population\Population table - 1970 - 2023 - Panda.xlsx", sheet_name='1990s_population (2)')

df_90.head(3)

,Year,Age,Total,Bumi,Chinese,Indian,Others,Non- Citizens,Male_Bumi,Male_Chinese,Male_Indian,Male_Others,Male_non Citizens,Female_Bumi,Female_Chinese,Female_Indian,Female_Others,Female_non Citizens
0,1991,0 - 4,2504.1,1716.4,510.8,169.9,33.1,73.9,882.8,265.0,87.0,17.1,38.5,833.6,245.9,82.9,16.0,35.4
1,1991,5 - 9,2363.5,1566.2,543.0,165.1,28.2,61.1,801.8,280.6,84.7,14.5,32.1,764.4,262.3,80.3,13.7,29.0
2,1991,10 - 14,2032.3,1272.3,536.2,156.8,23.8,43.2,648.5,276.2,79.3,12.1,22.6,623.8,260.0,77.5,11.7,20.6

In [2]:
#grand total_population
grand_total_population = df_90.groupby('Year').agg({
    'Total': 'sum'
}).reset_index()

#Grand total of male population
df_90['Male_Total'] = df_90[["Male_Bumi", "Male_Chinese", "Male_Indian", "Male_Others",	"Male_non Citizens"]].sum(axis=1)
df_90['Female_Total'] = df_90[["Female_Bumi", "Female_Chinese", "Female_Indian", "Female_Others", "Female_non Citizens"]].sum(axis=1)


#Group by 'Year' and aggregate totals
combined_pop = df_90.groupby('Year').agg({
    'Total': 'sum',
    'Male_Total': 'sum',
    'Female_Total': 'sum'
}).reset_index()

#rename column
combined_pop.columns = ['Year', 'Total Pop', 'Total Male', 'Total Female']

# Aggregate the values of age brackets across population

- use pivot() method to turn age brackets into thier own table
- Calculate total population - combine it to table

In [3]:
df_90.head(3)

,Year,Age,Total,Bumi,Chinese,Indian,Others,Non- Citizens,Male_Bumi,Male_Chinese,Male_Indian,Male_Others,Male_non Citizens,Female_Bumi,Female_Chinese,Female_Indian,Female_Others,Female_non Citizens,Male_Total,Female_Total
0,1991,0 - 4,2504.1,1716.4,510.8,169.9,33.1,73.9,882.8,265.0,87.0,17.1,38.5,833.6,245.9,82.9,16.0,35.4,1290.4,1213.8
1,1991,5 - 9,2363.5,1566.2,543.0,165.1,28.2,61.1,801.8,280.6,84.7,14.5,32.1,764.4,262.3,80.3,13.7,29.0,1213.7,1149.7
2,1991,10 - 14,2032.3,1272.3,536.2,156.8,23.8,43.2,648.5,276.2,79.3,12.1,22.6,623.8,260.0,77.5,11.7,20.6,1038.7,993.6

In [4]:
age_bracket = df_90.pivot(index='Year', columns='Age', values='Total')

age_bracket

Age,0 - 4,10 - 14,15 - 19,20 - 24,25 - 29,30 - 34,35 - 39,40 - 44,45 - 49,5 - 9,50 - 54,55 - 59,60 - 64,65 - 69,70 - 74,75 - 79,80 - 84,85+
Year,,,,,,,,,,,,,,,,,,
1991,2504.1,2032.3,1833.4,1683.5,1622.8,1457.0,1215.1,965.6,725.2,2363.5,610.9,487.0,370.9,266.1,183.5,107.9,72.7,45.6
1992,2523.6,2102.8,1887.6,1718.8,1647.7,1503.5,1272.5,1013.7,762.6,2412.2,624.5,505.6,385.5,275.7,191.0,121.3,72.2,46.5
1993,2555.1,2178.4,1927.4,1756.7,1680.2,1554.1,1322.8,1071.0,799.3,2458.5,643.3,525.4,400.4,287.3,194.7,124.2,72.4,50.4
1994,2592.4,2241.3,1979.2,1806.7,1706.5,1595.6,1376.6,1125.0,850.0,2495.5,660.6,543.4,414.9,301.0,198.5,129.7,71.9,52.9
1995,2629.2,2313.7,2031.0,1854.5,1741.5,1633.8,1428.4,1185.9,900.7,2510.4,679.9,561.7,430.2,315.7,203.7,134.9,72.0,54.5
1996,2664.2,2372.5,2089.9,1894.0,1779.9,1669.6,1481.5,1244.3,953.9,2529.4,711.3,579.8,446.3,329.6,210.5,136.8,73.7,55.5
1997,2695.3,2418.4,2155.4,1941.2,1815.1,1709.6,1528.7,1300.0,1010.9,2555.0,746.4,595.0,464.2,342.0,221.4,137.8,77.1,55.6
1998,2738.1,2458.6,2221.1,1984.3,1848.1,1752.4,1577.3,1350.6,1075.4,2585.0,783.7,612.7,483.2,353.1,235.0,137.6,81.1,56.2
1999,2773.4,2494.7,2282.2,2036.0,1885.2,1795.4,1623.8,1401.9,1141.1,2617.5,828.9,632.9,501.8,364.7,249.8,138.3,85.1,56.9
2000,2833.4,2523.7,2335.7,2088.5,1919.5,1837.1,1668.2,1451.0,1205.1,2646.0,877.7,657.9,519.3,378.3,264.2,142.7,87.9,58.8
2001,2801.2,2586.8,2428.0,2149.2,1948.1,1854.0,1702.6,1490.6,1250.1,2685.8,934.2,684.9,537.7,392.5,275.7,152.8,88.6,67.7
2002,2742.4,2640.4,2516.3,2231.0,1981.6,1869.4,1735.4,1530.7,1291.1,2714.7,992.7,718.2,553.8,411.0,284.7,166.6,87.8,74.8
2003,2668.8,2684.8,2594.1,2334.2,2019.9,1886.9,1765.6,1570.5,1331.3,2733.0,1048.0,759.5,568.0,432.9,291.5,181.6,88.1,79.4
2004,2609.5,2719.3,2660.9,2448.9,2068.3,1909.5,1792.2,1608.4,1373.0,2741.3,1097.4,807.3,583.6,454.4,299.1,194.9,91.3,82.0
2005,2555.8,2742.1,2719.1,2561.8,2135.3,1938.0,1816.0,1644.4,1416.2,2741.6,1142.2,857.8,605.4,472.4,311.1,205.4,97.7,83.5
2006,2524.7,2749.0,2764.4,2666.5,2226.1,1970.0,1838.5,1678.1,1459.2,2724.3,1185.3,908.0,635.2,488.8,326.0,213.1,106.9,85.9
2007,2513.5,2741.2,2801.9,2752.8,2349.5,2002.7,1862.5,1709.9,1501.3,2697.3,1229.2,953.8,675.1,499.5,346.7,216.5,118.0,87.0
2008,2512.5,2721.1,2828.3,2818.7,2498.5,2040.5,1889.9,1739.0,1541.5,2670.9,1276.0,993.5,723.8,506.8,371.4,218.0,129.4,87.9
2009,2515.0,2691.1,2841.8,2869.8,2652.2,2096.3,1920.9,1765.7,1579.3,2659.8,1323.9,1029.4,775.3,517.2,393.5,222.3,138.3,89.8
2010,2508.6,2654.0,2837.4,2912.0,2789.6,2181.7,1954.8,1791.5,1614.3,2659.5,1370.8,1066.0,823.5,538.0,409.3,233.4,144.3,100.1
2011,2505.6,2665.5,2852.6,2964.9,2871.6,2267.6,1977.3,1811.5,1643.4,2619.8,1415.7,1111.1,863.2,570.5,421.3,247.5,146.1,106.7
2012,2524.7,2670.0,2853.6,3017.5,2924.5,2368.5,1996.6,1827.7,1667.1,2581.8,1455.0,1159.8,896.8,613.0,426.5,267.8,144.5,114.5
2013,2559.3,2670.5,2867.8,3121.9,3027.7,2522.4,2046.8,1860.3,1695.4,2553.7,1496.7,1212.0,929.2,662.3,430.3,290.3,144.1,122.8
2014,2571.2,2665.5,2852.8,3182.5,3079.3,2643.1,2095.1,1880.3,1713.1,2536.9,1532.3,1260.2,962.2,708.5,439.6,308.1,148.4,129.5
2015,2601.6,2655.8,2846.7,3225.4,3135.9,2731.2,2158.2,1898.7,1727.9,2518.4,1560.3,1304.2,1000.4,748.6,460.9,319.6,158.3,134.0
2016,2630.4,2616.0,2862.7,3244.6,3189.4,2797.8,2236.8,1918.5,1741.3,2513.4,1585.1,1345.4,1040.8,785.1,490.0,330.7,167.0,138.7
2017,2613.7,2580.8,2871.1,3244.7,3238.7,2841.7,2334.5,1933.3,1755.4,2533.7,1604.4,1383.8,1085.1,815.7,527.9,334.9,180.5,142.6
2018,2595.3,2549.9,2871.9,3232.5,3281.8,2868.9,2438.7,1951.0,1768.9,2560.5,1619.5,1418.0,1130.6,843.0,572.1,337.7,196.1,145.8
2019,2580.0,2527.2,2857.6,3181.1,3270.7,2870.1,2512.8,1970.6,1774.3,2545.3,1627.3,1444.7,1171.4,870.2,612.7,346.9,210.1,150.2
2020,2519.5,2611.2,2839.5,2867.0,2891.6,2907.2,2742.6,2194.8,1843.7,2641.2,1586.0,1459.8,1152.1,917.4,611.4,329.3,194.6,138.5
2021,2445.5,2600.1,2800.7,2893.0,2851.7,2865.5,2777.9,2267.2,1870.2,2639.5,1605.5,1460.8,1208.7,951.3,645.0,353.6,201.2,139.1
2022,2374.2,2613.0,2781.9,2912.8,2835.0,2850.1,2777.0,2359.1,1893.9,2592.8,1638.3,1452.0,1254.3,974.5,674.5,377.1,203.1,134.5
2023,2345.7,2618.7,2775.4,3042.0,2926.9,2890.9,2845.7,2480.5,1955.3,2584.6,1674.9,1471.1,1288.8,1011.9,710.9,412.6,204.2,139.4

In [5]:
age_bracket.columns

Index([' 0 - 4', ' 10 - 14', ' 15 - 19', ' 20 - 24', ' 25 - 29', ' 30 - 34',
       ' 35 - 39', ' 40 - 44', ' 45 - 49', ' 5 - 9', ' 50 - 54', ' 55 - 59',
       ' 60 - 64', ' 65 - 69', ' 70 - 74', ' 75 - 79', ' 80 - 84', ' 85+'],
      dtype='object', name='Age')

In [6]:
total_per_year = age_bracket.sum(axis=1).reset_index()

total_per_year

    Year        0
0   1991  18547.1
1   1992  19067.3
2   1993  19601.6
3   1994  20141.7
4   1995  20681.7
5   1996  21222.7
6   1997  21769.1
7   1998  22333.5
8   1999  22909.6
9   2000  23495.0
10  2001  24030.5
11  2002  24542.6
12  2003  25038.1
13  2004  25541.3
14  2005  26045.8
15  2006  26550.0
16  2007  27058.4
17  2008  27567.7
18  2009  28081.6
19  2010  28588.8
20  2011  29061.9
21  2012  29509.9
22  2013  30213.5
23  2014  30708.6
24  2015  31186.1
25  2016  31633.7
26  2017  32022.5
27  2018  32382.2
28  2019  32523.2
29  2020  32447.4
30  2021  32576.5
31  2022  32698.1
32  2023  33379.5

**Combine total age bracket across years to new pivoted age table**

In [9]:
combined_age_total = pd.merge(total_per_year, age_bracket, on='Year')

#rename column
combined_age_total.columns = ['Year','Total', ' 0 - 4', ' 10 - 14', ' 15 - 19', ' 20 - 24', ' 25 - 29', ' 30 - 34',
       ' 35 - 39', ' 40 - 44', ' 45 - 49', ' 5 - 9', ' 50 - 54', ' 55 - 59',
       ' 60 - 64', ' 65 - 69', ' 70 - 74', ' 75 - 79', ' 80 - 84', ' 85+']

**Re-arrange 5-9 to sit after 0-4**

In [10]:
re_order = ['Year', 'Total', ' 0 - 4', ' 5 - 9', ' 10 - 14', ' 15 - 19', ' 20 - 24', ' 25 - 29',
                  ' 30 - 34', ' 35 - 39', ' 40 - 44', ' 45 - 49', ' 50 - 54', ' 55 - 59',
                  ' 60 - 64', ' 65 - 69', ' 70 - 74', ' 75 - 79', ' 80 - 84', ' 85+']

combined_age_total = combined_age_total[re_order]

combined_age_total

# new_file_path = r"C:\Users\ASYIKIN\OneDrive\Desktop\PYTHON FOR DATA ANALYSIS\PROJECTS\Population\age.xlsx"

# combined_age_total.to_excel(new_file_path, sheet_name='Sheet1', index=False)

,Year,Total,0 - 4,5 - 9,10 - 14,15 - 19,20 - 24,25 - 29,30 - 34,35 - 39,40 - 44,45 - 49,50 - 54,55 - 59,60 - 64,65 - 69,70 - 74,75 - 79,80 - 84,85+
0,1991,18547.1,2504.1,2363.5,2032.3,1833.4,1683.5,1622.8,1457.0,1215.1,965.6,725.2,610.9,487.0,370.9,266.1,183.5,107.9,72.7,45.6
1,1992,19067.3,2523.6,2412.2,2102.8,1887.6,1718.8,1647.7,1503.5,1272.5,1013.7,762.6,624.5,505.6,385.5,275.7,191.0,121.3,72.2,46.5
2,1993,19601.6,2555.1,2458.5,2178.4,1927.4,1756.7,1680.2,1554.1,1322.8,1071.0,799.3,643.3,525.4,400.4,287.3,194.7,124.2,72.4,50.4
3,1994,20141.7,2592.4,2495.5,2241.3,1979.2,1806.7,1706.5,1595.6,1376.6,1125.0,850.0,660.6,543.4,414.9,301.0,198.5,129.7,71.9,52.9
4,1995,20681.7,2629.2,2510.4,2313.7,2031.0,1854.5,1741.5,1633.8,1428.4,1185.9,900.7,679.9,561.7,430.2,315.7,203.7,134.9,72.0,54.5
5,1996,21222.7,2664.2,2529.4,2372.5,2089.9,1894.0,1779.9,1669.6,1481.5,1244.3,953.9,711.3,579.8,446.3,329.6,210.5,136.8,73.7,55.5
6,1997,21769.1,2695.3,2555.0,2418.4,2155.4,1941.2,1815.1,1709.6,1528.7,1300.0,1010.9,746.4,595.0,464.2,342.0,221.4,137.8,77.1,55.6
7,1998,22333.5,2738.1,2585.0,2458.6,2221.1,1984.3,1848.1,1752.4,1577.3,1350.6,1075.4,783.7,612.7,483.2,353.1,235.0,137.6,81.1,56.2
8,1999,22909.6,2773.4,2617.5,2494.7,2282.2,2036.0,1885.2,1795.4,1623.8,1401.9,1141.1,828.9,632.9,501.8,364.7,249.8,138.3,85.1,56.9
9,2000,23495.0,2833.4,2646.0,2523.7,2335.7,2088.5,1919.5,1837.1,1668.2,1451.0,1205.1,877.7,657.9,519.3,378.3,264.2,142.7,87.9,58.8
10,2001,24030.5,2801.2,2685.8,2586.8,2428.0,2149.2,1948.1,1854.0,1702.6,1490.6,1250.1,934.2,684.9,537.7,392.5,275.7,152.8,88.6,67.7
11,2002,24542.6,2742.4,2714.7,2640.4,2516.3,2231.0,1981.6,1869.4,1735.4,1530.7,1291.1,992.7,718.2,553.8,411.0,284.7,166.6,87.8,74.8
12,2003,25038.1,2668.8,2733.0,2684.8,2594.1,2334.2,2019.9,1886.9,1765.6,1570.5,1331.3,1048.0,759.5,568.0,432.9,291.5,181.6,88.1,79.4
13,2004,25541.3,2609.5,2741.3,2719.3,2660.9,2448.9,2068.3,1909.5,1792.2,1608.4,1373.0,1097.4,807.3,583.6,454.4,299.1,194.9,91.3,82.0
14,2005,26045.8,2555.8,2741.6,2742.1,2719.1,2561.8,2135.3,1938.0,1816.0,1644.4,1416.2,1142.2,857.8,605.4,472.4,311.1,205.4,97.7,83.5
15,2006,26550.0,2524.7,2724.3,2749.0,2764.4,2666.5,2226.1,1970.0,1838.5,1678.1,1459.2,1185.3,908.0,635.2,488.8,326.0,213.1,106.9,85.9
16,2007,27058.4,2513.5,2697.3,2741.2,2801.9,2752.8,2349.5,2002.7,1862.5,1709.9,1501.3,1229.2,953.8,675.1,499.5,346.7,216.5,118.0,87.0
17,2008,27567.7,2512.5,2670.9,2721.1,2828.3,2818.7,2498.5,2040.5,1889.9,1739.0,1541.5,1276.0,993.5,723.8,506.8,371.4,218.0,129.4,87.9
18,2009,28081.6,2515.0,2659.8,2691.1,2841.8,2869.8,2652.2,2096.3,1920.9,1765.7,1579.3,1323.9,1029.4,775.3,517.2,393.5,222.3,138.3,89.8
19,2010,28588.8,2508.6,2659.5,2654.0,2837.4,2912.0,2789.6,2181.7,1954.8,1791.5,1614.3,1370.8,1066.0,823.5,538.0,409.3,233.4,144.3,100.1
20,2011,29061.9,2505.6,2619.8,2665.5,2852.6,2964.9,2871.6,2267.6,1977.3,1811.5,1643.4,1415.7,1111.1,863.2,570.5,421.3,247.5,146.1,106.7
21,2012,29509.9,2524.7,2581.8,2670.0,2853.6,3017.5,2924.5,2368.5,1996.6,1827.7,1667.1,1455.0,1159.8,896.8,613.0,426.5,267.8,144.5,114.5
22,2013,30213.5,2559.3,2553.7,2670.5,2867.8,3121.9,3027.7,2522.4,2046.8,1860.3,1695.4,1496.7,1212.0,929.2,662.3,430.3,290.3,144.1,122.8
23,2014,30708.6,2571.2,2536.9,2665.5,2852.8,3182.5,3079.3,2643.1,2095.1,1880.3,1713.1,1532.3,1260.2,962.2,708.5,439.6,308.1,148.4,129.5
24,2015,31186.1,2601.6,2518.4,2655.8,2846.7,3225.4,3135.9,2731.2,2158.2,1898.7,1727.9,1560.3,1304.2,1000.4,748.6,460.9,319.6,158.3,134.0
25,2016,31633.7,2630.4,2513.4,2616.0,2862.7,3244.6,3189.4,2797.8,2236.8,1918.5,1741.3,1585.1,1345.4,1040.8,785.1,490.0,330.7,167.0,138.7
26,2017,32022.5,2613.7,2533.7,2580.8,2871.1,3244.7,3238.7,2841.7,2334.5,1933.3,1755.4,1604.4,1383.8,1085.1,815.7,527.9,334.9,180.5,142.6
27,2018,32382.2,2595.3,2560.5,2549.9,2871.9,3232.5,3281.8,2868.9,2438.7,1951.0,1768.9,1619.5,1418.0,1130.6,843.0,572.1,337.7,196.1,145.8
28,2019,32523.2,2580.0,2545.3,2527.2,2857.6,3181.1,3270.7,2870.1,2512.8,1970.6,1774.3,1627.3,1444.7,1171.4,870.2,612.7,346.9,210.1,150.2
29,2020,32447.4,2519.5,2641.2,2611.2,2839.5,2867.0,2891.6,2907.2,2742.6,2194.8,1843.7,1586.0,1459.8,1152.1,917.4,611.4,329.3,194.6,138.5
30,2021,32576.5,2445.5,2639.5,2600.1,2800.7,2893.0,2851.7,2865.5,2777.9,2267.2,1870.2,1605.5,1460.8,1208.7,951.3,645.0,353.6,201.2,139.1
31,2022,32698.1,2374.2,2592.8,2613.0,2781.9,2912.8,2835.0,2850.1,2777.0,2359.1,1893.9,1638.3,1452.0,1254.3,974.5,674.5,377.1,203.1,134.5
32,2023,33379.5,2345.7,2584.6,2618.7,2775.4,3042.0,2926.9,2890.9,2845.7,2480.5,1955.3,1674.9,1471.1,1288.8,1011.9,710.9,412.6,204.2,139.4